
mykit:
  delay:
    logpath: ../logs
    registry:
      enable: false
      namespace: io-mykit-delay
      serverList: 127.0.0.1:2181
    rocketmq:
      namesrvAddr: 127.0.0.1:9876
      filterSourceRoot: /home/
    activemq:
      # 连接的ActiveMQ failover:(tcp://localhost:61616,tcp://localhost:61617)
      brokerUrl: failover:(tcp://127.0.0.1:61616)
      username: admin
      password: admin123
      useExponentialBackOff: true
      useAsyncSend: true
      maximumRedeliveries: 1
      initialRedeliveryDelay: 3000
      backOffMultiplier: 2
      maximumRedeliveryDelay: 3000
      queue_pub_sub_domain: false
      topic_pub_sub_domain: true
    rqueue:
      #是否已集群模式运行 会涉及到分布式锁竞争的情况 默认为false
      cluster: false
      name: mykit-delay
      bucketSize: 4

spring:
  jmx:
    enabled: true
  application:
    name: 'mykit'
    version: '1.0.0'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mykit_delay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 30
    initialSize: 3
    maxWait: 60000
    maxIdle: 30
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
#    host: 192.168.175.11
#    password:
#    port: 6379
    timeout: 60000
    database: 1
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
    pool:
      max-idle: 300
      min-idle: 10
      max-active: 200
      max-wait: 10000

server:
  port: 6357

logging:
  config: classpath:config/logback.xml
